### ISSUE TITLE
Right-clicking Statistics crash

### ISSUE THREAD

**Issue by orudge** [ttdpatch/ttdpatch#26]
*Original issue: https://projects.tt-forums.net/issues/26*

---
TTDPatch Version: 2.5 beta 1
Patch Feature: morestatistics

Right-clicking the Statistics button in a company window causes a crash, because no help text is defined (IIRC). I imagine this shouldn't be too hard to fix?

**Comment by ttforums** [comment]
*Original author: Josef Drexler*
*Original date: 2006-04-08 03:05:52*

---
fixed in rev 33 for beta 3
